### ISSUE TITLE
Add Windows Build of leveldbjni-native

### ISSUE THREAD

**Issue by ajsutton** [Consensys/leveldbjni-native#3]
### Description

Add support for building leveldbjni native libraries targeting 32 and 64bit Windows.

### Acceptance Criteria

* Build includes an automated script that can be run by CircleCI (Powershell, CMD and Bash available)
* Builds on the CircleCI Windows executor (Windows Server 2019 with Visual Studio 2019)
* Resulting binary works on Windows 10 or above and Windows Server 2019 and above
* Includes Snappy support
* Builds a single binary library that staticly links snappy, leveldb and the leveldbjni native wrapper
* Works when loaded as a JNI library into Java 11 or later
* Should use snappy 1.1.9 or later and leveldb 1.22 or later

### Additional Information

For a complete list of software available on the Windows CircleCI executor see the bottom of
https://circleci.com/docs/2.0/hello-world-windows/

**Comment by lucassaldanha** [comment]
Closed as not planned.
